In [ ]:
expenses = [1100, 100, 120, 600, 2000]
print(sum(expenses))

3920


In [ ]:
expenses = [1100, 100, 120, 600, 2000]
print(expenses[0]) #索引從0開始
print(expenses[1])
print(expenses[-1]) #第一個
print(expenses[-2])

1100
100
2000
600


In [ ]:
my_list0 = [] #空串列
my_list1 = list() 
my_list2 = ['python', 'java', 'C#']
print(my_list2[2])

C#


In [ ]:
my_list2 = ['python', 'java', 'C#']
print(len(my_list2))
print(len(my_list2[1]))

3
4


In [ ]:
my_list2 = ['python', 'java', 'C#']
my_list2.append('java')
print(my_list2)

['python', 'java', 'C#', 'java']


In [ ]:
my_list2 = ['python', 'java', 'C#']
my_list2.insert(1,'java')
print(my_list2)

['python', 'java', 'java', 'C#']


In [ ]:
my_list2 = ['python', 'java', 'C#']
my_list2.remove('python') #移除指定元素
print(my_list2)
del my_list2[-1] #刪除全部的元素
print(my_list2)
my_list2.clear() #清除全部
print(my_list2)

['java', 'C#']
['java']
[]


In [ ]:
a=[10,20]
print(a*5)

[10, 20, 10, 20, 10, 20, 10, 20, 10, 20]


In [ ]:
a=[1,2,3,4,5,6,7,8,9]
b=a[0:3] #範圍取值，0,1,2不包含5
print(b)
c=a[0:9:2] #間隔2取值
print(c)
d = a[0: ]
print(d)
e = a[ :9]
print(e)
f = a[:] #取部分分值
print(f)

[1, 2, 3]
[1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a=[1,2,3,4,5,6,7,8,9]
del a[7:9] #刪除某範圍值, 7, 8
print(a)
print(min(a)) #最小值
print(max(a)) #最大值
print(a.index(1)) #找出1所在的第一個索引值
b=[1,0,0,1,1,1]
print(b.count(1)) #1出現的次數
a.reverse() #串列反轉
print(a)
a.sort() #串列由小到大排序,a的值會被改變
print(a)

[1, 2, 3, 4, 5, 6, 7]
1
7
0
4
[7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7]


In [ ]:
expenses = [110, 101, 121, 200, 205]
s=sorted(expenses) #expenses的值不會變
print(s, expenses)

[101, 110, 121, 200, 205] [110, 101, 121, 200, 205]


In [21]:
a_list=[10,20,30,40,50]
print(a_list*2)

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]


In [22]:
#numpy套件的ndarray型態,提供element-wise的操作
import numpy as np
a=np.array([10,20,30,40,50])
print(a*2)

[ 20  40  60  80 100]


In [23]:
a=np.array([10,20,30,40,50])
print(type(a))
print(a.shape) #ndaary的形狀
print(a.dtype) #資料的型態
print(a.ndim) #維度

<class 'numpy.ndarray'>
(5,)
int64
1


In [24]:
import numpy as np
z=np.zeros(6)
print(z)
print(np.empty((20,30,40)))
print(np.arange(5))

[0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0.

In [25]:
my_array=np.arange(20)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
0
[0 1 2 3 4]


In [29]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])
print(my_2d_array[:,1])
print(my_2d_array[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [31]:
my_array=np.arange(0,10)
print(my_array)
print(my_array.shape)
my_2d_array=my_array.reshape(2,5)
print(my_2d_array)
print((np.arange(0,50).reshape(5,10)))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [32]:
b=np.array([60, 6, 18, 40, np.nan])
print(b)

[60.  6. 18. 40. nan]


In [33]:
a_tuple=('python', 'java', 'SQL')
print(a_tuple)
b_list=['go', 'c#', 'vb']
b_tuple=tuple(b_list)
print(b_tuple)
print(b_tuple[0])

('python', 'java', 'SQL')
('go', 'c#', 'vb')
go


In [36]:
languages = {}
languages = {'name':'java', 'version':'3.7'} #索引值(鍵值)可以自訂
print(languages['name'])
print(languages['version'])
a={0:'python', 1:'java', 2:'SQL'}
print(a[0])
print(a[1])
print(a[2])
print(languages)
print(languages.keys())
print(languages.values())
print(languages.items())
print('name' in languages)

java
3.7
python
java
SQL
{'name': 'java', 'version': '3.7'}
dict_keys(['name', 'version'])
dict_values(['java', '3.7'])
dict_items([('name', 'java'), ('version', '3.7')])
True


In [38]:
import math
radius = eval(input("請輸入圓的直徑：")) #把輸入的字串變成數學計算型態
print("圓的面積為：", radius * radius * math.pi)

請輸入圓的直徑：5
圓的面積為： 78.53981633974483


In [39]:
import math
def circle_area(radius):
    area = radius * radius * math.pi
    return area

print(circle_area(5))

78.53981633974483


In [40]:
import os
print(os.getcwd()) #顯示目前所在的工作目錄

/content


In [41]:
#顯示目錄下的檔案
os.listdir(".")

['.config', 'sample_data']

In [42]:
#新增目錄
os.makedirs("test")
os.listdir(".")

['.config', 'test', 'sample_data']

In [43]:
#移除目錄
os.rmdir("test")
os.listdir(".")

['.config', 'sample_data']

In [46]:
a=open("a.txt","w") #新增檔案
a.write("This is a test2")
a.write("This is a test3\n")
a.write("This is a test4\n")
a.close() #關閉檔案

In [45]:
os.path.isfile("a.txt")

True

In [47]:
a=open("a.txt","r")
print(a.readline())
print(a.readline())
print(a.readline()) #多餘的命令，檔案只有4行
a.close()

This is a test2This is a test3

This is a test4




In [48]:
a=open("a.txt","r")
print(a.readlines())  #一次讀取多行，與a.read()命令不相同
a.close()

['This is a test2This is a test3\n', 'This is a test4\n']


In [49]:
#加上檔案是否存在的判斷
if os.path.isfile("a.txt"):
    a=open("a.txt","r")
    print(a.readlines())
    a.close()
else:
    print("檔案存在")

['This is a test2This is a test3\n', 'This is a test4\n']


In [50]:
if os.path.isfile("a.txt"):
    a=open("a.txt","r")
    for line in a:
        fields=line.split(" ") #以空白為切割欄位
        print(fields)
    a.close()
else:
    print("檔案存在")
        

['This', 'is', 'a', 'test2This', 'is', 'a', 'test3\n']
['This', 'is', 'a', 'test4\n']


In [52]:
a=open("a.txt", "a")
a.write("This is test8\n")
a.close()

In [53]:
a=open("a.txt","r")
print(a.readlines())
a.close()

['This is a test2This is a test3\n', 'This is a test4\n', 'This is test2\n', 'This is test8\n']


In [55]:
a=open("a.txt","r+")
a.write("This is a test10\n")
a.close()

In [56]:
a=open("a.txt","r")
print(a.readlines())
a.close()

['This is a test10\n', 'is is a test3\n', 'This is a test4\n', 'This is test2\n', 'This is test8\n']


In [58]:
if os.path.isfile("a.txt"):
    os.remove("a.txt")
    print("檔案刪除不成功")
else:
    print("找不到檔案")
print(os.path.isfile("a.txt"))

找不到檔案
False


In [61]:
a=5
b=10
if a<b:
    print(n)

NameError: ignored

In [66]:
a=5
b=10
try:
    if a<b:
        print(n)
except NameError as e:
    print("錯誤產生, 錯誤原因：",e)
except ZeroDivisionError:
    print("除以1錯誤")


錯誤產生, 錯誤原因： name 'n' is not defined


In [ ]:
a=5
b=10
try:
    if a>b: #改變比較條件，讓錯誤不發生
        print(n)
except:
    print("錯誤發生")
else:
    print("沒有錯誤發生時會執行的部分")

In [65]:
a=5
b=10
try:
    if a<b:
        print(n)
except:
    print("錯誤")

錯誤


In [68]:
a=5
b=10
try:
    if a>b: #改變比較條件，讓錯誤不發生
        print(n)
except:
    print("錯誤發生")
else:
    print("沒有錯誤發生時會執行的部分")
finally:
    print("不管有沒有錯誤一定會執行的部分")


沒有錯誤發生時會執行的部分
不管有沒有錯誤一定會執行的部分
